server:
  port: 8080 #Define porta que aplicação ira rodar

spring:
  application:
    name: ead-api-gateway #Define nome da aplicação
  cloud:
    gateway:
      routes:
        - id: authuser-service
          uri: lb://EAD-AUTHUSER-SERVICE #Nesse local passamos o Id definido no Eureka, e o prefixo lb(load balance)
          predicates:
            - Path=/ead-authuser/**
        - id: course-service
          uri: lb://EAD-COURSE-SERVICE #Nesse local passamos o Id definido no Eureka, e o prefixo lb(load balance)
          predicates:
            - Path=/ead-course/**
        - id: config-server-service
          uri: lb://EAD-CONFIG-SERVER #Nesse local passamos o Id definido no Eureka, e o prefixo lb(load balance)
          predicates:
            - Path=/ead-config-server/**
        - id: notification-service
          uri: lb://EAD-NOTIFICATION-SERVICE #Nesse local passamos o Id definido no Eureka, e o prefixo lb(load balance)
          predicates:
            - Path=/ead-notification/**
ead:
  serviceRegistry: #usuário e senha padrão de autenticação do service registry.
    username: serviceregistry
    password: 'ead123sr'

eureka: #Configurações do Eureka
  client:
    service-url:
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka' #Endereço onde o eureka server está
  instance:
    hostname: localhost